version: '2.1'

volumes:
  cache:
    driver: local

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m

  postgres-db:
    image: postgres
    mem_limit: 512m
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 2s
      retries: 60
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass bWlyb3NsYXY=
    volumes:
      - cache:/data